---
name: cicd
on: 
  - push
jobs:
  build-packages:
    name: Build Packages
    runs-on:
      - build
      #- linux
      #- self-hosted
      - ${{ matrix.distro }}
      - ${{ matrix.arch }}
    strategy:
      matrix:
        distro: [
          # TODO: add back debian9
          debian8, debian10,
          centos7, centos8,
          amazon2,
          fedora31, fedora32
        ]
        arch: [ amd64 ]
    steps:
      - name: Checkout sources 
        uses: actions/checkout@v2

      - name: Build DEB packages
        if: ${{ startsWith(matrix.distro, 'debian') || startsWith(matrix.distro, 'ubuntu') }}
        run: make deb
      - name: Build RPM packages
        if: ${{ startsWith(matrix.distro, 'centos') || startsWith(matrix.distro, 'amazon') || startsWith(matrix.distro, 'fedora') }}
        run: make rpm
      - name: Collect artifacts
        run: repobuild/collect_artifacts.sh
      - name: Upload artifacts
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:    ${{ secrets.AWS_REGION }}
        if: ${{ startsWith(matrix.distro, 'debian') || startsWith(matrix.distro, 'ubuntu') }}
        run: repobuild/upload.sh
          --source repobuild/artifacts/
          --bucket artifacts.assur.io
          --target /linux/elastio-snap/$(git rev-parse --abbrev-ref HEAD)/${GITHUB_RUN_NUMBER}/deb
          --exclude *GPG-KEY
#      - if: ${{ startsWith(matrix.distro, 'centos') || startsWith(matrix.distro, 'amazon') || startsWith(matrix.distro, 'fedora') }}
#      - run: repobuild/upload.sh
#          --source repobuild/artifacts/
#          --bucket artifacts.assur.io
#          --target /linux/elastio-snap/${DRONE_SOURCE_BRANCH}/${DRONE_BUILD_NUMBER}/rpm
